### ISSUE TITLE
Unable to compile on Ubuntu 14.04 TLS

### ISSUE THREAD

**Issue by ElderFain** [IBM-Swift/Kitura#346]
It appears the libpthread_workqueue doesn't function quite right on Ubuntu 14.04 TLS per discussion here -- http://comments.gmane.org/gmane.comp.lang.swift.corelibs/318. This results in the make/install failing

`git submodule init && git submodule update && sh ./autogen.sh && ./configure --with-swift-toolchain=${SWIFT_PATH}/usr --prefix=${SWIFT_PATH}/usr && make && sudo make install`

queue.c:226:22: error: use of undeclared identifier 'WORKQ_BG_PRIOQUEUE'        
.dgq_wq_priority = WORKQ_BG_PRIOQUEUE,

**Comment by ElderFain** [comment]
Maybe related to https://github.com/apple/swift-corelibs-libdispatch/issues/65 ?

**Comment by dgrove-oss** [comment]
I think if you pick up the fix to configure.ac from https://github.com/apple/swift-corelibs-libdispatch/pull/64/files it will work.   Unfortunately the current tip of the master branch of libdispatch doesn't build correctly.

**Comment by ElderFain** [comment]
I tried it with the experimental/foundation branch,but it still fails to compile (in a different location)

https://gist.github.com/ElderFain/76e3d34d447e066054b967f793fb3618

**Comment by ElderFain** [comment]
@dgrove-oss Any suggestions? I tried with the latest and still see the same issue. I tried a few variations & tweaks without much success.

**Comment by dgrove-oss** [comment]
Is it possible you already have libdisaptch installed in your swift tool chain?  (Look for /usr/lib/swift/linux/x86_64/Dispatch.swiftmodule and/or /usr/lib/swift/dispatch/module.map).  I've seen swiftc crash when building Dispatch.swift if there is already a version of the Dispatch module installed.    If it is installed and you need to recompile libdispatch, you have to uninstall Dispatch from the swift tool chain first, build the new one, then install it.

**Comment by kweinmeister** [comment]
@ElderFain is this issue still reproducible with Kitura 0.12?

**Comment by ElderFain** [comment]
Using the latest CF Swift build pack on Kitura 0.13 I was able to deploy, however its using .tar.gz's of compiled libdispatch, basically bypassing this issue.

**Comment by dfirsht** [comment]
I believe this issue is resolved, feel free to reopen or submit a new issue if you have any other problems.
