### ISSUE TITLE
swift build error

### ISSUE THREAD

**Issue by sieder** [IBM-Swift/Kitura#1149]
Swift version 4.0-dev

so whenever I run "swift build" this issue pops out 

```
error: manifest parse error(s): 
/home/user/myFirstProject/Package.swift:11:3: error: type 'Package.Dependency' has no member 'Package'
.Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 7)
                                                                                                                            
```
I am assuming it might be a different syntax to use inside Package.swift for building in Swift 4, because it worked on swift 3.1.

Package.swift
```
// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "myFirstProject",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
	.Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 7)
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "myFirstProject",
            dependencies: []),
    ]
)

```

UPDATE 

```
`// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "myFirstProject",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
	.package(url: "https://github.com/IBM-Swift/Kitura.git", from: "1.0.0")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "myFirstProject",
            dependencies: []),
    ]
)`
```

issue: Fetching https://github.com/IBM-Swift/Kitura.git
error: could not find executable for 'git'

**Comment by youming-lin** [comment]
Do you have `git` installed and in your system's `PATH`?

**Comment by sieder** [comment]
Yea, thanks, I missed that, it did remove that issue and returned this after running swift build.

```
Compile Swift Module 'myFirstProject' (1 sources)
/home/meraki/Apps/myFirstProject/Sources/myFirstProject/main.swift:1:8: error: no such module 'Kitura'
import Kitura
       ^
error: terminated(1): /home/user/Downloads/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-09-08-a-ubuntu16.04/usr/bin/swift-build-tool -f /home/meraki/Apps/myFirstProject/.build/debug.yaml main
```

**Comment by youming-lin** [comment]
For that, you have to add `Kitura` to the target's dependencies, like so:
```swift
targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "myFirstProject",
            dependencies: ["Kitura"]),
    ]
```

**Comment by sieder** [comment]
It crossed out the issue and again it throws a new one, 

`Compile Swift Module 'SSLService' (1 sources)
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "shim.h"
         ^
/home/user/Apps/myFirstProject/.build/checkouts/OpenSSL.git--5358878159534755497/shim.h:20:10: error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^
/home/user/Apps/myFirstProject/.build/checkouts/BlueSSLService.git--3933832815804725236/Sources/SSLService.swift:26:9: error: could not build C module 'OpenSSL'
        import OpenSSL
               ^`

**Comment by youming-lin** [comment]
I'm assuming you are using Linux?

If so, do you have `OpenSSL` installed? Specifically, you need these two packages: `openssl` and `libssl-dev`.
https://github.com/IBM-Swift/OpenSSL/blob/master/Package%40swift-4.swift#L25

**Comment by sieder** [comment]
Yes, you right, I installed both libcurl4-openssl-dev and libssl-dev and finally it worked. Thanks @youming-lin !

**Comment by youming-lin** [comment]
You're welcome! I'll close this issue then.

**Comment by jhoughjr** [comment]
I'm getting the Package.dependency has no member Package as well. git is in my system path and everything involving it works.
