### ISSUE TITLE
Remove usage of `catch (let error as NSError)` from repos.

### ISSUE THREAD

**Issue by carlbrown** [IBM-Swift/Kitura#1043]
From @youming-lin via Slack: The non-exhaustive error catching on Linux 3.1 is intentional: https://bugs.swift.org/browse/SR-3872

A few of our repos hit this snag already, might be good idea to remove `NSError` from our code in the future, as its "bridged" behavior on 3.0 may have been a bug

**Comment by youming-lin** [comment]
To clarify, here is an example. All examples were tested on Ubuntu 16.04.

main.swift:
```swift
import Foundation

func test() {
    do {
#if os(Linux) && !swift(>=3.1)
        let _ = try RegularExpression(pattern: "abc", options: [])
#else
        let _ = try NSRegularExpression(pattern: "abc", options: [])
#endif
    }
    catch let error as NSError {
        print(error)
    }
}
```

This code compiles on 3.0.2 but errors on 3.1 03-24 with this error message:
```
main.swift:8:17: error: errors thrown from here are not handled because the enclosing catch is not exhaustive
        let _ = try NSRegularExpression(pattern: "abc", options: [])
```

Now, take a look at another example.
main2.swift:
```swift
import Foundation

func test() {
    do {
#if os(Linux) && !swift(>=3.1)
        let _ = try RegularExpression(pattern: "abc", options: [])
#else
        let _ = try NSRegularExpression(pattern: "abc", options: [])
#endif
    }
    catch {
        let err = error as NSError
    }
}
```

This code WILL ERROR on both 3.0.2 and 3.1 03-24. The error on 3.0.2 is:
```
main2.swift:12:19: error: missing _bridgeNSError
        let err = error as NSError
                  ^
swift: /home/buildnode/disk2/workspace/oss-swift-3.0-package-linux-ubuntu-16_04/swift/lib/Sema/CSApply.cpp:3223: swift::Expr *(anonymous namespace)::ExprRewriter::visitCoerceExpr(swift::CoerceExpr *): Assertion `!failed && "Not convertible?"' failed.
0  swift           0x00000000035c3c08 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift           0x00000000035c4367
2  libpthread.so.0 0x00007fb424654390
3  libc.so.6       0x00007fb422d82428 gsignal + 56
4  libc.so.6       0x00007fb422d8402a abort + 362
5  libc.so.6       0x00007fb422d7abd7
6  libc.so.6       0x00007fb422d7ac82
7  swift           0x0000000000fd9e35
8  swift           0x0000000000fcab50
9  swift           0x0000000000fcef40
10 swift           0x00000000010f8e55 swift::Expr::walk(swift::ASTWalker&) + 69
11 swift           0x0000000000fc7458 swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::Expr*, swift::Type, bool, bool, bool) + 504
12 swift           0x0000000000f19d0e swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::TypeLoc, swift::ContextualTypePurpose, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::ExprTypeCheckListener*, swift::constraints::ConstraintSystem*) + 766
13 swift           0x0000000000f1ddd0 swift::TypeChecker::typeCheckBinding(swift::Pattern*&, swift::Expr*&, swift::DeclContext*) + 352
14 swift           0x0000000000f1dfed swift::TypeChecker::typeCheckPatternBinding(swift::PatternBindingDecl*, unsigned int) + 285
15 swift           0x0000000000f33d6d
16 swift           0x0000000000f300ed
17 swift           0x0000000000f2ffbd swift::TypeChecker::typeCheckDecl(swift::Decl*, bool) + 157
18 swift           0x0000000000f9b004
19 swift           0x0000000000f9b393
20 swift           0x0000000000f9af8e
21 swift           0x0000000000f99303 swift::TypeChecker::typeCheckFunctionBodyUntil(swift::FuncDecl*, swift::SourceLoc) + 339
22 swift           0x0000000000f99160 swift::TypeChecker::typeCheckAbstractFunctionBodyUntil(swift::AbstractFunctionDecl*, swift::SourceLoc) + 32
23 swift           0x0000000000f99e73 swift::TypeChecker::typeCheckAbstractFunctionBody(swift::AbstractFunctionDecl*) + 179
24 swift           0x0000000000f54387
25 swift           0x0000000000f54f29 swift::performTypeChecking(swift::SourceFile&, swift::TopLevelContext&, swift::OptionSet<swift::TypeCheckingFlags, unsigned int>, unsigned int, unsigned int) + 1289
26 swift           0x0000000000cc74d6 swift::CompilerInstance::performSema() + 3542
27 swift           0x00000000007e6c36
28 swift           0x00000000007e5b41 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2737
29 swift           0x00000000007ab263 main + 2787
30 libc.so.6       0x00007fb422d6d830 __libc_start_main + 240
31 swift           0x00000000007a8909 _start + 41
Stack dump:
0.	Program arguments: /home/ylin/.swiftenv/versions/3.0.2/usr/bin/swift -frontend -interpret main2.swift -target x86_64-unknown-linux-gnu -disable-objc-interop -color-diagnostics -module-name main2 
1.	While type-checking 'test' at main2.swift:3:1
2.	While type-checking declaration 0x502f6b8 at main2.swift:12:9
3.	While type-checking expression at [main2.swift:12:19 - line:12:28] RangeText="error as N"
Aborted (core dumped)
```

The error on 3.1 03-24 is:
```
main2.swift:12:25: error: 'Error' is not convertible to 'NSError'; did you mean to use 'as!' to force downcast?
        let err = error as NSError
                  ~~~~~~^~~~~~~~~~
                        as!
```

These examples show that in reality, bridging Error to NSError is NOT ALLOWED on Linux, and that being able to compile the first example on Linux 3.0.2 is due to a bug in the compiler.

**Comment by youming-lin** [comment]
List of all occurrences of `let error as NSError` in IBM-Swift org: https://github.com/search?utf8=%E2%9C%93&q=org%3AIBM-Swift+%22let+error+as+NSError%22&type=Code

**Comment by youming-lin** [comment]
Here is clearer example demonstrating a runtime crash on Ubuntu 3.0.2 toolchain:

main3.swift
```swift
import Foundation

enum VendingMachineError: Error {
    case invalidSelection
    case insufficientFunds(coinsNeeded: Int)
    case outOfStock
}

func test() {
  do {
    throw VendingMachineError.outOfStock 
  } 
  catch let error as NSError {
    print(error)
  } 
}

test()
```

The code throws an `Error`, with a corresponding catch block that checks for errors of `NSError` type. This compiles on 3.0.2 Ubuntu toolchain (due to the compiler bug previously mentioned), but during execution, a crash is observed:

```
[15:14:14] ylin@delayserver:~/Desktop$ swift main3.swift 
0  swift           0x00000000035c3c08 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift           0x00000000035c4367
2  libpthread.so.0 0x00007f6ae2049390
3  libswiftCore.so 0x00007f6ade7f4738 globalinit_33_FD9A49A256BEB6AF7C48013347ADC3BA_token3 + 0
Stack dump:
0.	Program arguments: /home/ylin/.swiftenv/versions/3.0.2/usr/bin/swift -frontend -interpret main3.swift -target x86_64-unknown-linux-gnu -disable-objc-interop -color-diagnostics -module-name main3 
Segmentation fault (core dumped)
```

The same code WILL NOT compile on Ubuntu 3.1 toolchain due to the non-exhaustive catch block error:

```
[15:14:00] ylin@delayserver:~/Desktop$ swift main3.swift 
main3.swift:11:5: error: error is not handled because the enclosing catch is not exhaustive
    throw VendingMachineError.outOfStock 
    ^
```
