### ISSUE TITLE
Build fails for swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a-ubuntu14.04

### ISSUE THREAD

**Issue by capJavert** [IBM-Swift/Kitura#230]
After running make, or swift build -Xcc -fblock i get the following error message:

Linking Library:  .build/debug/LoggerAPI.a
Compiling Swift Module 'KituraSys' (4 sources)
Linking Library:  .build/debug/KituraSys.a
Linking Library:  .build/debug/KituraNet.a
Linking Library:  .build/debug/KituraRouter.a
Linking Library:  .build/debug/HeliumLogger.a
Compiling Swift Module 'LoggerSample' (1 sources)
Linking Executable:  .build/debug/LoggerSample
Linking Library:  .build/debug/XCTest.a
Linking Executable:  .build/debug/KituraSample
/usr/bin/ld: cannot find -lcurlHelpers
/usr/bin/ld: cannot find -lhttpParserHelper
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): ["/home/javert/swift/usr/bin/swift-build-tool", "-f", "/home/javert/work_work/Kitura/.build/debug/Kitura.o/llbuild.yaml"]

As I see it it fails on final linking for some reason and then it does not create KituraSample file.

Ante

**Comment by vadimeisenbergibm** [comment]
@capJavert could you please specify which OS you work on, which swift version you use and which Kitura branch you work on?

**Comment by capJavert** [comment]
As mentioned in title, i am working on ubuntu 14.04, swift version 3.0-dev snapshot-2016-02-08 and Kitura master branch.

**Comment by vadimeisenbergibm** [comment]
@capJavert That makes sense :) On master branch please use `make`. On develop branch please use `swift build -Xcc -fblocks`

**Comment by capJavert** [comment]
i get error module Dispatch requires 'blocks' feature.. when i use Makefile. This is why I tried to do it with swift build -Xcc -fblocks

**Comment by vadimeisenbergibm** [comment]
@capJavert Sorry for my confusion, I see now that you are using make, and then swift build -Xcc -fblocks.
Please verify that you have libcurlHelpers.a and libhttpParserHelper.a in .build/debug folder.
If they are there, run `swift build -Xcc -fblocks -Xlinker -L./.build/debug -Xlinker -ldispatch`

**Comment by capJavert** [comment]
I have both files in my .build/debug folder, after i run command i get this:

Linking Executable:  .build/debug/KituraSample
/home/javert/work_work/Kitura/.build/debug/KituraSys.a(Queue.swift.o): In function `_TFC9KituraSys5QueuecfT4typeOS_9QueueType5labelGSqSS__S0_':
/home/javert/work_work/Kitura/Packages/Kitura-sys-0.2.1/Sources/KituraSys/Queue.swift:43: undefined reference to `_TF8Dispatchg25DISPATCH_QUEUE_CONCURRENTVs14COpaquePointer'
/home/javert/work_work/Kitura/Packages/Kitura-sys-0.2.1/Sources/KituraSys/Queue.swift:44: undefined reference to `_TF8Dispatchg21DISPATCH_QUEUE_SERIALVs14COpaquePointer'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): ["/home/javert/swift/usr/bin/swift-build-tool", "-f", "/home/javert/work_work/Kitura/.build/debug/Kitura.o/llbuild.yaml"]

**Comment by vadimeisenbergibm** [comment]
Do you want to try the latest Swift snapshot from swift.org? swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a. It works for me on master on ubuntu 14.04.

**Comment by capJavert** [comment]
yupi yay... this worked, changed to swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a, rebuild Dispatch and the rest and after running swift build -Xcc -fblocks -Xlinker -L./.build/debug -Xlinker -ldispatch it worked!!

thanks a lot!!
